config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :confirmations => "users/confirmations"} do
    match '/logout' => 'devise/sessions#destroy'
  end

  resources :letters do
    member do
      get :like
    end
  end

  get 'profile_picture/twitter/:twitter_handle', to: 'profile_picture#twitter', as: :twitter_image

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @letter = Letter.new
    @letters = Letter.order(Arel.sql('(SELECT COUNT(*) FROM likes WHERE (letters.id=likes.letter_id)) DESC'))
                   .includes([:likes, :user]).page(params[:page]).per(15)
    @recent_letters = Letter.limit(15).order('created_at DESC').includes(:user)
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def markdown(text)
      options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
      syntax_highlighter(Redcarpet.new(text, *options).to_html).html_safe
  end

  def syntax_highlighter(html)
      doc = Nokogiri::HTML(html)
      doc.search("//pre[@lang]").each do |pre|
        pre.children.each do |child|
          next unless child.name == 'code'
          child.set_attribute('class', "language-#{pre[:lang]}")
        end
      end
      doc.to_s
  end

end

app/views/home/index.html.haml
.row
  .span8
    %h3 I Love Ruby Because ..
    = form_for @letter do |f|
      = f.text_area :description, class: 'reasonText'
      .markTest.pull-left
        = link_to "Markdown supported", "http://daringfireball.net/projects/markdown/", target: '_blank'
      - if user_signed_in?
        = f.submit 'Submit', class: 'btn primary pull-right'
      -else
        = link_to 'Submit', '#', class: 'btn primary pull-right disabled', rel: 'popover', data: {title: 'Oops!!', content: 'You need to login first to submit!!'}


%hr
.row
  .span8
    .letters
      - @letters.each do |letter|
        %ul.breadcrumb.letters{ style: "display: flex; padding: 20px" }
          %li
            .voteCount.pull-left
              %div{class: "countNumber #{letter.id}"}
                = letter.likes.count
              - if user_signed_in?
                = link_to 'UpVote', '#', class: "btn likeButton #{letter.like_by?(current_user) ? 'disabled' : ''}", data: {url: like_letter_path(letter)}
              - else
                = link_to 'UpVote', '#', class: 'btn', rel: 'popover', data: {content: "You need to login first to Like it. ", title: 'Oops !!'}


            .personalInfo.pull-right
              .pull-right.names
                = letter.user.name
                %br
                %strong
                  - if letter.user.twitter_identity.present?
                    - twitter_identity = letter.user.twitter_identity
                    %a{ href: "https://www.twitter.com/#{twitter_identity.handle}", target: "_blank" }
                      = "@#{twitter_identity.handle}"
                  - if letter.user.github_identity.present?
                    - github_identity = letter.user.github_identity
                    %a{ href: "https://www.github.com/#{github_identity.handle}", target: "_blank" }
                      = "@#{github_identity.handle}"
                %br
                %small.timeAgo
                  = link_to letter_path(letter) do
                    = time_ago_in_words letter.created_at
                    ago
              .pull-right.thumbnail.imageWrapper{ style: 'max-height: 50px; max-width: 50px' }
                = get_profile_image(letter.user)


        -#          TODO refactor this
        - unless letter.user_id == 43
          .letterDescription
            = markdown(letter.description)
        - else
          .letterDescription43
            = markdown(letter.description)
        %br
        %div
          %div.pull-left
            - if letter.user.twitter_identity.present?
              - twitter_identity = letter.user.twitter_identity
              %a.twitter-share-button{"data-size": "large", "data-hashtags": "whyloveruby", "data-url": "#{root_url}",
                   href: "https://twitter.com/share", class: 'pull-right',
                   "data-text": "Here is @#{twitter_identity.handle}\'s reason to love Ruby. -  #{letter_url(letter)}\n Tell us yours at" }
            - if letter.user.github_identity.present?
              - github_identity = letter.user.github_identity
              %a.twitter-share-button{"data-size": "large", "data-hashtags": "whyloveruby", "data-url": "#{root_url}",
                   href: "https://twitter.com/share", class: 'pull-right',
                   "data-text": "Here is @#{github_identity.handle}\'s reason to love Ruby. -  #{letter_url(letter)}\n Tell us yours at" }
          .clr
          :javascript
                   !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
          .letterActions.pull-right
            = link_to "More", letter_path(letter), class: 'btn-link'
            - if user_signed_in?
              - if(current_user.id.to_i == letter.user_id.to_i)
                |
                = link_to "Edit", edit_letter_path(letter)
        %br
        %hr
    = paginate @letters